name: CI

on:
  push:
    tags:
      - '*.*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_FAKE_KEY: ${{ secrets.FAKE_KEY }}

    steps:
      - name: Set version name
        run: echo ::set-env name=ORG_GRADLE_PROJECT_VERSION_NAME::${GITHUB_REF:11}

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Build and check
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-outputs
          path: app/build/outputs
