name: CI

on:
  push:
    tags:
      - '*.*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_FAKE_KEY: ${{ secrets.FAKE_KEY }}
      ORG_GRADLE_PROJECT_VERSION_NAME: ${{ GITHUB_REF:10 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set secret layout
        run: 'echo "$LAYOUT" > app/src/main/res/layout/activity_main.xml'
        shell: bash
        env:
          LAYOUT: ${{ secrets.SECRET_LAYOUT }}

      - name: Decrypt keystore
        run: ./.github/scripts/decrypt_keystore.sh
        env:
          KEYSTORE_GPG_PASSPHRASE: ${{ secrets.KEYSTORE_GPG_PASSPHRASE }}

      - name: Setup app signing configuration
        run: 'echo "$KEYSTORE_PROPERTIES" > release/keystore.properties'
        env:
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Build and check
        run: ./gradlew :app:bundleRelease --stacktrace

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-outputs
          path: app/build/outputs
